name: Docker Image CI/CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t lklynet/injectly:${{ github.ref_name }} -t lklynet/injectly:latest .

    - name: Push Docker Image
      run: |
        docker push lklynet/injectly:${{ github.ref_name }}
        docker push lklynet/injectly:latest